### ISSUE TITLE
Absence of line-wrapping for long subgame name causes an unlimited column shift

### ISSUE THREAD

**Issue by kilbith** [minetest/serverlist#11]
![capture d ecran de 2016-01-30 14-26-10](https://cloud.githubusercontent.com/assets/7883281/12695970/c212be1a-c75d-11e5-9238-72b37ced2c86.png)

**Comment by rubenwardy** [comment]
That long subgame name is a bug, it should stip all the directories out.

**Comment by rubenwardy** [comment]
That also doesn't happen to me, firefox:

![does_not_happen_to_me](https://cloud.githubusercontent.com/assets/2122943/12696166/e9ab3aae-c75a-11e5-81bb-33a204d08d86.png)

**Comment by sfan5** [comment]
e37149a8344de2c6fa35bd6ba913f1a91a41707a
