### ISSUE TITLE
Rename this repository to "serverlist"

### ISSUE THREAD

**Issue by luk3yx** [minetest/serverlist#41]
I think the name "serverlist" is much more intuitive than "master-server".

 - Why is this a master server when [ContentDB](https://github.com/minetest/contentdb) isn't? What happens if/when Minetest starts interacting with even more web services?
 - Calling this "serverlist" brings the repository name in line with the [`serverlist_url` configuration entry](https://github.com/minetest/minetest/blob/af22dd86e3867a35e9e5ab911faa6e1e7671729d/minetest.conf.example#L1158) and [the first line of README.md](https://github.com/minetest/master-server/blob/master/README.md).
 - GitHub seems to automatically redirect old repository URLs, this *shouldn't* break anything.

**Comment by rubenwardy** [comment]
Done, on agreement from sfan5
