### ISSUE TITLE
Hide double protocol servers from v4 list

### ISSUE THREAD

**Issue by Festus1965** [minetest/serverlist#48]
`
			# reduction to 40% for servers that support both legacy (v4) and v5 clients
			if server["proto_min"] <= 32 and server["proto_max"] > 36:
				points *= 0.4`
better way: list them just/only in 0.,4 version, and then fully (no penalty)

reason:
as of my research most gamer there come from our old 0.4 itself, the not updated 0.4 versions on apps,
and there own client ...

as there own client seam NOT to separate between 0.4 and 5.x and as of listed multiproto server also in 5.0 I see a huge amount of mismatches connects on my server as soon getting place 3 or better

as of my research there are near no gamer left in 5.x they might splay there ... and they still can scroll down to the 0.4 server part ... it is much better that a few 5.x users scroll then all wrong servers 5.x are flooded with mismatched connections, that also have no fun, are blocked from joining they cant understand why!

**Comment by sfan5** [comment]
The client filters the list by protocol version on its own, the server-side has no direct influence on this.

But even *if* this was done consider that Multicraft servers do support both 0.4 and 5.0 clients, not showing them would be plainly incorrect. It would also be very unfair to people who play on Multicraft servers who suddenly won't be able to find them in the list.

> as there own client seam NOT to separate between 0.4 and 5.x
> I see a huge amount of mismatches connects on my server as soon getting place 3 or better

Minetest also does this, servers with too old protocol versions are still displayed and only "grayed out". You can still attempt to connect to them.
![grafik](https://user-images.githubusercontent.com/1042418/132139748-1c474907-0ffb-4291-ba5f-4707ba6f59e5.png)

**Comment by Festus1965** [comment]
yes, funnily your wright, also a 0.4 can try to connect 5.x and a 5.x client can try to connect to 0.4.x

but there are differences in how many users are using 5.x (may be just 10% left) and 0.4.x (with all the mobile apps and even bad closes) the REST of 90%.

But I will see the now surprising changes, how they will workout in reality.
* the 80% rule is still there, I have to guess now as the thread wasn't in answers
* the penalty with 40% is not balanced, as age and stability (each 8 points) does not have anything to do with the problem ... depending on my research on gamer per protocol it might be like 10% of gamer points onto 5.x list, and rest gamer points are from and so into 0.4.x list counting.

**Comment by Festus1965** [comment]
IT is still fact, that on web serverlist Minecraft NO Minetest server is seen,
and
on MC clients, MT servers are behind ... whatever gamer they have.

After a year now, why we mt are still so NICE ?

**Comment by Festus1965** [comment]
April 2022
still on http://servers.multicraft.world/

NO any original Minetest server is shown ...

why then still here ? after they prof clear they will not show ours.

They close the door to their own roots,
so we should close the door to their ... special when see what country is running it, and owner of Multicraft itself.

**Comment by Bituvo** [comment]
I think we should remove the reduction of points if a server supports legacy clients, because there are a lot of players who still use these versions. EdgyNet hosting is especially affected by this, and unless they have insanely high player amounts and low ping, they are placed very low on the list.

**Comment by Festus1965** [comment]
> if a server supports legacy clients, ...
the problem with 0.4.x client accepting server is they are never free from also add or cheating copy apps,
compare to 5.x. I know yet and also have seen so far only one client, that can be blocked.

Maybe we let server choice what list they want to be listed ONLY, depending on their most clients,
but a bit tricky to program this here
but they have easy the change to stop the 0.4.x or 5.x protocol to support = automatic listed full on ONE version.

And as they still can fish in 3 lists (0.4.x, 5.x and their own alone) I see no need to do,
but 5.x server admins should be aware of the impact if same listed ... they will instant take 50% of the top 10-15 ranks,
as of their most more powerful server and more player available.

And as I have shown with my server, it is quit easy to switch from MT to MC ... but have to deal with then very much 0.4.x player including the one use the add show to switch the IP and so make our ban or EUban mods useless also.

In my case I would show them all ONLY in 0.4.x list, as of my own experience (my server for about 3 months with MC) they get most player from there.
So its most fair and right listet in the clients ... (the browserlist is different and does not matter)

**Comment by mckaygerhard** [comment]
you all only see the point of the administration.. _"oh there are many fake clients"_  ...  _"oh there are many cheaters"_ ... _"oh i have undesired players.."_ .. blah blah...

I give you all the hard blow of reality... all children and adults, **the vast majority want is to meet people and enter ALIVE servers full of people**... that is why multiprotocol servers are more used and will still be for many years... and if they break the old protocol will only remain in the depths of oblivion!

the creator multicraft and take this as advantage the first years.. now is exchanged cutoff of the older protocoll with the favor of contributions from minetest infiltrators.. 

TH[IS IS THE REALITY: ad picture shows:

1. there are only few 0.4.X server but only one have MORE THAT 40 players: NASA server (check picture)
2. there are huge amount of 5.X server but ony the multiprotocol servers are often used! rest are just so dead!
3. **players wants to play with huge amount of people.. and huge amount of people liked those broken things!**

![image](https://github.com/minetest/serverlist/assets/1571724/885bc78c-3a4c-49d0-9e0b-8ef1707ed97f)
