### ISSUE TITLE
`flask.send_file` api change in flask > 2.0

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/serverlist#56]
Breaking change in flask > 2.0 (the requirements.txt specifies `>= 1.1.0`)

https://flask.palletsprojects.com/en/2.2.x/api/?highlight=send_from_directory#flask.send_file (in "Changelog")
```
Changed in version 2.0: max_age replaces the cache_timeout parameter. conditional is enabled and max_age is not set by default.
```

Line in question:
https://github.com/minetest/serverlist/blob/218f8d9bc5b2b4e7edf21e731a53cbca8377783d/server.py#L58

Solutions:
* pin flask dependency to `< 2.0`
* switch to `max_age` parameter

**Comment by augmentmoogi** [comment]
Should we also lock flask version? - what triggered this to fail now?
