### ISSUE TITLE
Publishing two Luanti servers on the same host with different addresses

### ISSUE THREAD

**Issue by zJudGenie** [minetest/serverlist#68]
It seems that I cannot publish two Luanti servers on the servers list if they are hosted on the same server, we tried to publish our main server AES with the address `luanti.aes.land` and then we wanted to keep the old address `minetest.aes.land` alive so players with our server in the favorite list can still find us.

This does not seem to work as the entry in the server list is overwritten, I think because it is indexed by the IP https://github.com/minetest/serverlist/blob/master/server.py#L138 am I right?

luanti.aes.land and minetest.aes.land addresses point to the same IP.
Thank you.

**Comment by sfan5** [comment]
The primary key for servers on the list is the IP of the announcer and the server port. So this is indeed not possible.
The other problem with duplicate servers is that you "cheat" yourself a second place on the list, which is not a desirable thing to allow.

**Comment by rubenwardy** [comment]
Luanti does not support virtual hosting - so the same IP address and port will always be the same server.

When I changed the CTF address, I listed the new address on the server list but kept the old address off the list but alive so it still worked for those that had it saved

**Comment by Zughy** [comment]
> kept the old address off the list but alive so it still worked for those that had it saved

But if it results offline in the list, people won't even try to connect.

Switching would cause a decrease in players, but at the same time we'd like to avoid "minetest" in the IP

**Comment by rubenwardy** [comment]
I didn't notice any decrease in players after switching the domain name. I don't think luanti shows "offline" on a saved server listing so the user isn't explicitly discouraged

**Comment by sfan5** [comment]
Here's how unlisted servers show:
![grafik](https://github.com/user-attachments/assets/e2909744-c7be-4ec4-b73a-cc497b612077)

**Comment by sfan5** [comment]
The thing is our main menu only has two possible states: "online according to public list" and "unknown".
It should be possible to make that clearer design-wise, so that players aren't misled and think it means "offline".
